apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
spec:
  type: NodePort
  selector:
    app: petclinic
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080


#kubectl apply -f petclinic-service-lb.yaml
#kubectl get svc
# https://647a-176-43-165-93.ngrok-free.app/ --> ngrok ile publicIP üstünden erişilebilir. Önce ELK ile denedim fakat yetiştiremedim.
